# Generated by Django 5.2 on 2025-08-14 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estabelecimento_aliasestabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='aliasestabelecimento',
            name='mestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='core.aliasestabelecimento'),
        ),
    ]
