# Generated by Django 5.2 on 2025-08-14 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_estabelecimento_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrao_regex', models.CharField(help_text="Regex aplicada sobre o texto normalizado (ex.: r'\\bAMAZON\\b|\\bAMAZON MARKET\\b')", max_length=255)),
                ('prioridade', models.PositiveIntegerField(default=100, help_text='Menor número = regra aplicada primeiro.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['prioridade', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='aliasestabelecimento',
            options={'ordering': ['nome_base', 'nome_alias']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'ordering': ['nome_fantasia']},
        ),
        migrations.AddField(
            model_name='aliasestabelecimento',
            name='nome_base',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Forma normalizada do alias para agrupar variações (preenchido automaticamente).', max_length=200),
        ),
        migrations.AlterField(
            model_name='aliasestabelecimento',
            name='mestre',
            field=models.ForeignKey(blank=True, help_text='Alias principal ao qual esta variante pertence (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='core.aliasestabelecimento'),
        ),
        migrations.AlterField(
            model_name='aliasestabelecimento',
            name='nome_alias',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='aliasestabelecimento',
            constraint=models.UniqueConstraint(fields=('estabelecimento', 'nome_alias'), name='uix_estabelecimento_nome_alias'),
        ),
        migrations.AddField(
            model_name='regraalias',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_alias', to='core.estabelecimento'),
        ),
    ]
