# Generated by Django 5.2 on 2025-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_regraalias_alter_aliasestabelecimento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('corretora', 'Corretora'), ('fintech', 'Fintech'), ('cooperativa', 'Cooperativa'), ('outro', 'Outro')], default='banco', max_length=20)),
            ],
        ),
    ]
