# Generated by Django 5.2 on 2025-08-29 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=140)),
                ('padrao_regex', models.CharField(help_text='Regex aplicada sobre o texto normalizado (alias_base/descrição).', max_length=255)),
                ('prioridade', models.PositiveIntegerField(default=100, help_text='Menor número = regra aplicada primeiro.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['prioridade', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nivel', 'nome']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Macro'), (2, 'Sub')], default=1),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='categoria_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimentos', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('categoria_pai', 'nome'), name='uix_categoria_pai_nome'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria_pai__isnull', True), ('nivel', 1)), models.Q(('categoria_pai__isnull', False), ('nivel', 2)), _connector='OR'), name='chk_categoria_nivel_vs_pai'),
        ),
        migrations.AddField(
            model_name='regracategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_categoria', to='core.categoria'),
        ),
    ]
