# Generated by Django 5.2 on 2025-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_regracategoria_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['-adulto', 'nome']},
        ),
        migrations.AddField(
            model_name='membro',
            name='adulto',
            field=models.BooleanField(default=True),
        ),
    ]
