# Generated by Django 5.2 on 2025-09-03 13:16

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('valor_alvo', models.DecimalField(decimal_places=2, help_text='Valor necessário para cumprir a meta (sem projeção de juros).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor-alvo')),
                ('data_alvo', models.DateField(verbose_name='Data-alvo')),
                ('prioridade', models.PositiveSmallIntegerField(default=3, help_text='Maior número = maior prioridade (ex.: 1..5).', verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída'), ('adiada', 'Adiada'), ('cancelada', 'Cancelada')], default='ativa', max_length=16, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-status', 'data_alvo', '-prioridade', 'descricao'],
                'indexes': [models.Index(fields=['status'], name='meta_status_idx'), models.Index(fields=['data_alvo'], name='meta_data_idx'), models.Index(fields=['-prioridade'], name='meta_prio_desc_idx')],
            },
        ),
    ]
