# Generated by Django 5.2 on 2025-08-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='conta',
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
