# Generated by Django 5.2 on 2025-08-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraOcultacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome descritivo da regra (ex: 'BB Rende Fácil')", max_length=100)),
                ('padrao', models.CharField(help_text='Texto ou padrão para buscar na descrição', max_length=200)),
                ('tipo_padrao', models.CharField(choices=[('exato', 'Texto exato'), ('contem', 'Contém o texto'), ('inicia_com', 'Inicia com'), ('termina_com', 'Termina com'), ('regex', 'Expressão regular')], default='contem', help_text='Como aplicar o padrão', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar a regra temporariamente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Ocultação',
                'verbose_name_plural': 'Regras de Ocultação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
