# Generated by Django 5.2 on 2025-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0004_regraocultacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='oculta_manual',
            field=models.BooleanField(default=False),
        ),
    ]
