# Generated by Django 5.2 on 2025-08-15 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0005_transacao_oculta_manual'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='membro',
            field=models.ForeignKey(blank=True, help_text='Quem está relacionado a este gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.membro'),
        ),
    ]
