# Generated by Django 5.2 on 2025-08-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0006_transacao_membro'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='membro',
        ),
        migrations.AddField(
            model_name='transacao',
            name='membros',
            field=models.ManyToManyField(blank=True, help_text='Quem está relacionado a este gasto', related_name='transacoes', to='core.membro'),
        ),
    ]
