# Generated by Django 5.2 on 2025-08-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0007_remove_transacao_membro_transacao_membros'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('padrao', models.CharField(help_text='Texto ou regex para encontrar na descrição', max_length=255)),
                ('tipo_padrao', models.CharField(choices=[('exato', 'Igual a'), ('contem', 'Contém'), ('inicia_com', 'Inicia com'), ('termina_com', 'Termina com'), ('regex', 'Expressão Regular')], default='contem', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Ordem de execução (menor primeiro aplica antes)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='regras_membro', to='core.membro')),
            ],
            options={
                'ordering': ['prioridade', 'nome'],
            },
        ),
    ]
