# Generated by Django 5.2 on 2025-08-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0008_regramembro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regramembro',
            options={},
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='membros',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='padrao',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='regramembro',
            name='tipo_padrao',
        ),
    ]
