# Generated by Django 5.2 on 2025-08-26 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0009_alter_regramembro_options_remove_regramembro_ativo_and_more'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regramembro',
            options={'ordering': ('prioridade', 'nome'), 'verbose_name': 'Regra de Membro', 'verbose_name_plural': 'Regras de Membro'},
        ),
        migrations.AddField(
            model_name='regramembro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regramembro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regramembro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regramembro',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='regras_membro', to='core.membro'),
        ),
        migrations.AddField(
            model_name='regramembro',
            name='nome',
            field=models.CharField(default='sem nome', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regramembro',
            name='padrao',
            field=models.CharField(default='Sem nome', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regramembro',
            name='prioridade',
            field=models.PositiveIntegerField(default=100, help_text='Quanto menor, mais cedo esta regra é avaliada.'),
        ),
        migrations.AddField(
            model_name='regramembro',
            name='tipo_padrao',
            field=models.CharField(choices=[('exato', 'Texto exato'), ('contem', 'Contém o texto'), ('inicia_com', 'Inicia com'), ('termina_com', 'Termina com'), ('regex', 'Expressão regular')], default='contem', max_length=20),
        ),
        migrations.AddField(
            model_name='regramembro',
            name='tipo_valor',
            field=models.CharField(choices=[('nenhum', 'Sem condição de valor'), ('igual', 'Igual a'), ('maior', 'Maior que'), ('menor', 'Menor que')], default='nenhum', max_length=10),
        ),
        migrations.AddField(
            model_name='regramembro',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='regramembro',
            index=models.Index(fields=['ativo', 'prioridade'], name='conta_corre_ativo_abcf0c_idx'),
        ),
    ]
