# Generated by Django 5.2 on 2025-08-26 18:17

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0010_alter_regramembro_options_regramembro_ativo_and_more'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas', to='core.membro'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('instituicao', 'agencia', 'numero'), name='uniq_conta_por_banco_agencia_numero'),
        ),
    ]
