# Generated by Django 5.2 on 2025-08-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0011_conta_membro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='titular',
        ),
    ]
