# Generated by Django 5.2 on 2025-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0012_remove_conta_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='fitid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
