# Generated by Django 4.2.11 on 2025-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0013_alter_transacao_fitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='oculta',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
