# Generated by Django 5.2 on 2025-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0014_transacao_oculta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='oculta_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
