# Generated by Django 5.2 on 2025-08-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0015_alter_transacao_oculta_manual'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conta',
            name='uniq_conta_por_banco_agencia_numero',
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(fields=('instituicao', 'agencia', 'numero'), name='uniq_conta_por_banco_agencia_numero'),
        ),
    ]
