# Generated by Django 5.2 on 2025-08-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0016_remove_conta_uniq_conta_por_banco_agencia_numero_and_more'),
        ('core', '0008_regracategoria_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.categoria'),
        ),
    ]
