# Generated by Django 5.2 on 2025-09-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0017_transacao_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='conta_corrente.conta')),
            ],
            options={
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['conta', 'data'], name='conta_corre_conta_i_738e2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('conta', 'data'), name='uniq_saldo_por_conta_e_data')],
            },
        ),
    ]
