# Generated by Django 5.2 on 2025-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_corrente', '0018_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='pagamento_cartao',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
