# Generated by Django 5.2 on 2025-08-19 15:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissor', models.CharField(blank=True, max_length=60, null=True)),
                ('titular', models.CharField(blank=True, max_length=120, null=True)),
                ('cartao_final', models.CharField(max_length=8)),
                ('fechado_em', models.DateField()),
                ('vencimento_em', models.DateField()),
                ('competencia', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('arquivo_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('fonte_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('import_batch', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['competencia', 'cartao_final'], name='cartao_cred_compete_d4eee6_idx'), models.Index(fields=['fechado_em'], name='cartao_cred_fechado_d92ab3_idx')],
                'constraints': [models.UniqueConstraint(fields=('cartao_final', 'competencia'), name='uniq_fatura_por_cartao_competencia')],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('pais', models.CharField(blank=True, max_length=8, null=True)),
                ('secao', models.CharField(blank=True, max_length=40, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moeda', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_moeda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxa_cambio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('etiqueta_parcela', models.CharField(blank=True, max_length=20, null=True)),
                ('parcela_num', models.PositiveIntegerField(blank=True, null=True)),
                ('parcela_total', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hash_linha', models.CharField(max_length=40)),
                ('hash_ordem', models.PositiveSmallIntegerField(default=1)),
                ('is_duplicado', models.BooleanField(default=False)),
                ('fitid', models.CharField(blank=True, max_length=100, null=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='cartao_credito.faturacartao')),
                ('membros', models.ManyToManyField(blank=True, related_name='lancamentos_cartao', to='core.membro')),
            ],
            options={
                'indexes': [models.Index(fields=['fatura', 'data'], name='cartao_cred_fatura__e26f9f_idx')],
                'constraints': [models.UniqueConstraint(fields=('fatura', 'hash_linha', 'hash_ordem'), name='uniq_lcto_por_fatura_hash_ordem')],
            },
        ),
    ]
