# Generated by Django 5.2 on 2025-05-06 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('titular', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('fechada', models.BooleanField(default=False)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartao_credito.cartao')),
            ],
            options={
                'unique_together': {('cartao', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField(default=1)),
                ('parcela_atual', models.IntegerField(default=1)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartao_credito.fatura')),
            ],
        ),
    ]
