# Generated by Django 5.2 on 2025-08-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacartao',
            name='bandeira',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
