# Generated by Django 5.2 on 2025-08-28 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0002_faturacartao_bandeira'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturacartao',
            name='titular',
        ),
        migrations.AddField(
            model_name='faturacartao',
            name='membro',
            field=models.ForeignKey(
                to='core.membro',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='faturas_cartao',
            ),
        ),
    ]
