# Generated by Django 5.2 on 2025-08-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0003_remove_faturacartao_titular_faturacartao_membro'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(blank=True, max_length=60, null=True)),
                ('cartao_final', models.CharField(max_length=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='faturacartao',
            name='uniq_fatura_por_cartao_competencia',
        ),
        migrations.RemoveIndex(
            model_name='faturacartao',
            name='cartao_cred_compete_d4eee6_idx',
        ),
        migrations.RemoveField(
            model_name='faturacartao',
            name='bandeira',
        ),
        migrations.RemoveField(
            model_name='faturacartao',
            name='cartao_final',
        ),
        migrations.RemoveField(
            model_name='faturacartao',
            name='emissor',
        ),
        migrations.RemoveField(
            model_name='faturacartao',
            name='membro',
        ),
        migrations.AddField(
            model_name='cartao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.instituicaofinanceira'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes', to='core.membro'),
        ),
        migrations.AddField(
            model_name='faturacartao',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartao_credito.cartao'),
        ),
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['competencia', 'cartao'], name='cartao_cred_compete_a95e29_idx'),
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'competencia'), name='uniq_fatura_por_cartao_competencia'),
        ),
        migrations.AddIndex(
            model_name='cartao',
            index=models.Index(fields=['cartao_final'], name='cartao_cred_cartao__20dfe5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartao',
            index=models.Index(fields=['membro'], name='cartao_cred_membro__1a7a65_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartao',
            constraint=models.UniqueConstraint(fields=('instituicao', 'bandeira', 'cartao_final'), name='uniq_cartao_instituicao_bandeira_final'),
        ),
    ]
