# Generated by Django 5.2 on 2025-08-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0004_cartao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturacartao',
            name='cartao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='cartao_credito.cartao'),
        ),
    ]
