# Generated by Django 5.2 on 2025-08-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0005_alter_faturacartao_cartao'),
        ('core', '0007_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraMembroCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_padrao', models.CharField(choices=[('exato', 'Texto exato'), ('contem', 'Contém o texto'), ('inicia_com', 'Inicia com'), ('termina_com', 'Termina com'), ('regex', 'Expressão regular')], default='contem', max_length=20)),
                ('padrao', models.CharField(max_length=200)),
                ('tipo_valor', models.CharField(choices=[('nenhum', 'Sem condição de valor'), ('igual', 'Igual a'), ('maior', 'Maior que'), ('menor', 'Menor que')], default='nenhum', max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(default=100, help_text='Quanto menor, mais cedo esta regra é avaliada.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='regras_membro_cartao', to='core.membro')),
            ],
            options={
                'verbose_name': 'Regra de Membro (Cartão)',
                'verbose_name_plural': 'Regras de Membro (Cartão)',
                'ordering': ('prioridade', 'nome'),
                'indexes': [models.Index(fields=['ativo', 'prioridade'], name='cartao_cred_ativo_ee18ca_idx')],
            },
        ),
    ]
