# Generated by Django 5.2 on 2025-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0007_lancamento_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='oculta_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
