# Generated by Django 5.2 on 2025-08-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao_credito', '0008_lancamento_oculta_manual'),
        ('core', '0008_regracategoria_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.categoria'),
        ),
    ]
