# Generated by Django 5.2 on 2025-09-09 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_regracategoria_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='core.instituicaofinanceira')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos', to='core.membro')),
            ],
            options={
                'ordering': ['instituicao__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='investimentos.investimento')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='investimento',
            constraint=models.UniqueConstraint(fields=('instituicao', 'nome', 'membro'), name='uniq_investimento_instituicao_nome_membro'),
        ),
        migrations.AddIndex(
            model_name='saldoinvestimento',
            index=models.Index(fields=['investimento', 'data'], name='idx_saldo_inv_data'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoinvestimento',
            unique_together={('investimento', 'data')},
        ),
    ]
