# Generated by Django 5.2 on 2025-09-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_regracategoria_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('financiamento', 'Financiamento'), ('emprestimo', 'Empréstimo'), ('consorcio', 'Consórcio'), ('outro', 'Outro')], default='financiamento', max_length=20)),
                ('valor_contratado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('taxa_juros', models.DecimalField(blank=True, decimal_places=3, help_text='% a.a. (opcional)', max_digits=6, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passivos', to='core.instituicaofinanceira')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passivos', to='core.membro')),
            ],
            options={
                'ordering': ['instituicao__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoPassivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('passivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='passivos.passivo')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='passivo',
            constraint=models.UniqueConstraint(fields=('instituicao', 'nome', 'membro'), name='uniq_passivo_instituicao_nome_membro'),
        ),
        migrations.AddIndex(
            model_name='saldopassivo',
            index=models.Index(fields=['passivo', 'data'], name='idx_saldo_passivo_data'),
        ),
        migrations.AlterUniqueTogether(
            name='saldopassivo',
            unique_together={('passivo', 'data')},
        ),
    ]
