# Generated by Django 5.2 on 2025-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passivo',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveConstraint(
            model_name='passivo',
            name='uniq_passivo_instituicao_nome_membro',
        ),
        migrations.RemoveField(
            model_name='passivo',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='passivo',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='passivo',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='passivo',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='passivo',
            name='taxa_juros',
        ),
        migrations.RemoveField(
            model_name='passivo',
            name='valor_contratado',
        ),
        migrations.RemoveField(
            model_name='saldopassivo',
            name='saldo_devedor',
        ),
        migrations.AddField(
            model_name='saldopassivo',
            name='valor_devido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor devido'),
            preserve_default=False,
        ),
    ]
